gcoppariE3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inicio.urls')),
    path('eventos/', include('eventos.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios'))
   # path('chat/', include('chat.urls', namespace='chat')),  
    ]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
             

inicio/urls.py
from django.urls import path

from inicio.views import (
    inicio, 
    buscar_persona, 
    crear_persona, 
    about,verpersona, 
    eliminarpersona, 
    editarpersona)

from inicio.views import inicio, buscar_persona, crear_persona, about



app_name ='inicio'
urlpatterns = [
    path('', inicio, name='inicio'),
    path('buscar-persona/', buscar_persona, name='buscar_persona'),
    path('crear-persona/', crear_persona, name='crear_persona'),
    path('about/', about, name='about'),
    path('verpersona/<int:persona_id>/', verpersona, name='verpersona'),
    path('eliminarpersona/<int:persona_id>/', eliminarpersona, name='eliminarpersona'),
    path('editarpersona/<int:persona_id>/', editarpersona, name='editarpersona')
    
    ]

 

inicio/models.py
from django.db import models

class Persona(models.Model):
    dni = models.IntegerField()
    nombre = models.CharField(max_length=20)
    apellido = models.CharField(max_length=20)
    empresa = models.CharField(max_length=20)
    

    def __str__(self):
        # para mostra la lista datos
        return f'{self.nombre }{' '}{ self.apellido }{' - '}{ self.empresa }'
    
    

inicio/forms.py
from django import forms
from .models import Persona

class AutoFormularioBase(forms.Form):
    dni = forms.CharField() #(max_length=9)
    nombre = forms.CharField(max_length=20)
    apellido = forms.CharField(max_length=20)
    empresa = forms.CharField(max_length=20)  

class CrearPersonaFormulario(AutoFormularioBase):...  
    
class EditarPersonaFormulario(forms.ModelForm):
    class Meta:
        model = Persona  # Vinculamos el formulario al modelo Persona
        fields = ['dni', 'nombre', 'apellido', 'empresa']  # Campos a mostrar en el formulario
      
class BuscarPersonaFormulario(forms.Form):
        apellido = forms.CharField(max_length=20,required=False)
        empresa = forms.CharField(max_length=20,required=False)
        

inicio/views.py
from django.http import HttpResponse
from django.template import Template, Context, loader

from django.shortcuts import render, redirect, get_object_or_404
from inicio.models import Persona
from inicio.forms import CrearPersonaFormulario,BuscarPersonaFormulario,EditarPersonaFormulario
from django.contrib.auth.decorators import login_required


def inicio(request):
    return render(request, 'inicio/index.html')



def buscar_persona(request):
    persona = None  # Inicializamos persona como None por defecto
    formulario = BuscarPersonaFormulario(request.GET)

    if formulario.is_valid():
        apellido = formulario.cleaned_data.get('apellido')
        empresa = formulario.cleaned_data.get('empresa')

        # Realizar la búsqueda solo si se han proporcionado datos
        persona = Persona.objects.filter(apellido__icontains=apellido, empresa__icontains=empresa)

    return render(request, 'inicio/buscar_persona.html', {
        'form': formulario,
        'persona': persona,  # Pasamos la variable persona al template
    })



def crear_persona(request):
    
    formulario = CrearPersonaFormulario(request.POST)
    if request.method == 'POST':
       
        
        if formulario.is_valid():
            data = formulario.cleaned_data
            
            # Crear y guardar el objeto 
            persona = Persona(dni=data.get('dni'), nombre=data.get('nombre'), apellido=data.get('apellido'), empresa=data.get('empresa'))
            persona.save()
            return redirect('inicio:buscar_persona')

        else:
            # En caso de que falten datos
            return render(request, 'inicio/crear_persona.html', {'error': 'Por favor completa todos los campos'})

    return render(request, 'inicio/crear_persona.html',{'form': formulario})




def about(request):
    return render(request, 'inicio/about.html')


def verpersona(request,persona_id):
     # Buscamos la persona por su ID o devolvemos un 404 si no existe)
    persona=Persona.objects.get( id=persona_id)
     # Pasamos la persona al template
    return render(request, 'inicio/verpersona.html', {'p': persona})





def eliminarpersona(request,persona_id):
   
    persona=Persona.objects.get( id=persona_id)
    persona.delete()
    return redirect('inicio:buscar_persona')

          
            
           


def editarpersona(request, persona_id):
    # Obtener la persona con el ID proporcionado
    persona = Persona.objects.get(id=persona_id)
    
    # Inicializar el formulario con los datos actuales de la persona
    formulario = EditarPersonaFormulario(initial={
        'dni': persona.dni,
        'nombre': persona.nombre,
        'apellido': persona.apellido,
        'empresa': persona.empresa
    })
    
    # Si la solicitud es POST (se ha enviado el formulario)
    if request.method == 'POST':
        formulario = EditarPersonaFormulario(request.POST, instance=persona)
        
        # Si el formulario es válido, actualizamos los datos de la persona
        if formulario.is_valid():
            formulario.save()  # Guardamos los datos actualizados
            return redirect('inicio:buscar_persona')  # Redirigimos tras guardar
    
    # Renderizamos la plantilla con el formulario
    return render(request, 'inicio/editarpersona.html', {
        'persona': persona,
        'form': formulario
    })

inicio/templates/inicio/about.html
{% extends "inicio/index.html" %}
{% load static %}

{% block title_head %}             
  About 
{% endblock title_head%} 


{% block h1_header %}
  About
{% endblock %}    





{% block main %}

<body>
    <div class="container">
        <h1>Sistema de Gestión de Ingreso a coworking</h1>
        <h2>Descripción</h2>
        <p>
            El <strong>Sistema de Gestión de Ingreso a coworking</strong> está diseñado para facilitar y optimizar el control de acceso de personas a unidades temporales de trabajo. Permite gestionar el registro, validar ingresos y controlar el acceso en tiempo real, garantizando seguridad y eficiencia.
        </p>

        <h2>Características principales</h2>
        <div class="features">
            <ul>
                <li>Registro de Usuarios</li>
                <li>Validación Ingreso</li>
                <li>Monitoreo en tiempo real del ingreso</li>
                <li>Integración con plataformas de reservas</li>
                <li>Administracion de Salas</li>
            </ul>
        </div>

        <h2>Desarrolladores</h2>
        <p>
            Este sistema ha sido desarrollado por el equipo de <strong> Gustavo Coppari </strong>, al cual se especializa en soluciones tecnológicas para eventos. Para más información, visita nuestro sitio web: <a href="https://lala.com">www.lala.com</a>.
        </p>

        <h2>Soporte Técnico</h2>
        <p>
            Si tienes preguntas o necesitas asistencia técnica, por favor contáctanos a través de soporte@tusitio.com</a> o visita nuestra página de soporte</a>.
        </p>

        <h2>Licencia</h2>
        <p>
            Este software está licenciado bajo <strong>Prueba1</strong>. 
        </p>

        <div class="credits">
            <p>Agradecemos a todos los colaboradores que participaron en la creación de esta plataforma.</p>

        </div>
    </div>
</body>



{% endblock main %}

inicio/templates/inicio/buscar_persona.html
{% extends "inicio/index.html" %}
{% load static %}

{% block title_head %}             
   Lista de Usuarios
{% endblock title_head%} 


{% block h1_header %}
Lista de Usuarios
{% endblock %}    

{% block main %}

<form method="GET" action="">
    <h2> </h2>
    {{ form.as_p }}
    <button type="submit">Buscar</button>
</form>

{% if persona %}
    <h2>Resultados de la búsqueda:</h2>
    <ul>
        {% for p in persona %}
            <li>{{ p.nombre }} {{ p.apellido }} - {{ p.empresa }}  |  
                <a href="{% url 'inicio:verpersona' p.id %}"> Ver Mas </a>  |  
                <a href="{% url 'inicio:eliminarpersona' p.id %}"> Elimina </a>  |  
                <a href="{% url 'inicio:editarpersona' p.id %}"> Editar </a></li> 
        {% endfor %}
    </ul>
{% else %}
    <p>No se encontraron resultados.</p>
{% endif %}
{% endblock main %}

inicio/templates/inicio/crear_persona.html
{% extends "inicio/index.html" %}
{% load static %}

{% block title_head %}             
   Nuevo Usuario
{% endblock title_head%} 


{% block h1_header %}
    Nuevo Usuario
{% endblock %}    

{% block main %}

<form action="{% url 'inicio:crear_persona' %}" method="POST" >

    {% csrf_token %} 

    <br><br>
    Usuario:
    <br><br>
  
    <label for="id_dni">DNI:</label>
    <input type="number" name="dni" id="id_dni" required="false">

    <label for="id_nombre">Nombre:</label>
    <input type="text" name="nombre" id="id_nombre" required="false">

    <label for="id_apellido">Apellido:</label>
    <input type="text" name="apellido" id="id_apellido" required="false">

    <label for="id_empresa">Empresa:</label>
    <input type="text" name="empresa" id="id_empresa" required="false">

    <button type="submit">Enviar</button>

{% comment %} 
   {{form}}

   
<input type="submit" value="Enviar">    
 
    <button>Enviar</button> 
{% endcomment %}

</form>




{% endblock main %}

inicio/templates/inicio/editarpersona.html
{% extends "inicio/index.html" %}
{% load static %}

{% block title_head %}             
 Editar Usuario
{% endblock title_head%} 


{% block h1_header %}
    Editar: {{persona}}
{% endblock %}    

{% block main %}

<form action="{% url 'inicio:editarpersona' persona.id %}" method="POST" >

    {% csrf_token %} 

    <br><br>
  {% comment %} 

    <label for="id_dni">DNI:</label>
    <input type="number" name="dni" id="id_dni" required="false">

    <label for="id_nombre">Nombre:</label>
    <input type="text" name="nombre" id="id_nombre" required="false">

    <label for="id_apellido">Apellido:</label>
    <input type="text" name="apellido" id="id_apellido" required="false">

    <label for="id_empresa">Empresa:</label>
    <input type="text" name="empresa" id="id_empresa" required="false">

    <button type="submit">Enviar</button>
    {% endcomment %}

   {{form}}

   
<input type="submit" value="Enviar">    
 
   

</form>




{% endblock main %}

inicio/templates/inicio/index.html
{% extends "base.html" %} 

{% block title_head %}             
Coworking
{% endblock title_head%} 


{% block h1_header %}
Espacio Coworking                      
{% endblock %}     

inicio/templates/inicio/verpersona.html
{% extends "base.html" %}

{% load static %}

{% block title_head %}              
  Ver Usuario 
{% endblock title_head%} 


{% block h1_header %}
  {{p}}
{% endblock %}    


{% block main %}
<ul>
    <li>
       DNI: {{p.dni}} 
    </li>
    <li>
       Apellido: {{p.apellido}}
    </li>
    <li>
       Nombre: {{p.nombre}} 
    </li>

</ul>   

{% endblock main%}   