eventos/urls.py
from django.urls import path
from eventos import views

app_name='eventos'

urlpatterns = [
    path('fiestas/crear/', views.CrearFiesta.as_view(), name='crear_fiesta'),
    path('fiestas/', views.ListadoFiesta.as_view(), name='listado_fiesta'),
    path('fiestas/<int:pk>', views.VerFiesta.as_view(), name='ver_fiesta'),
    path('fiestas/<int:pk>/editar', views.EditarFiesta.as_view(), name='editar_fiesta'),
    path('fiestas/<int:pk>/eliminar', views.EliminarFiesta.as_view(), name='eliminar_fiesta')
    
]

gcoppariE3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inicio.urls')),
    path('eventos/', include('eventos.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios'))
   # path('chat/', include('chat.urls', namespace='chat')),  
    ]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
             

inicio/urls.py
from django.urls import path

from inicio.views import (
    inicio, 
    buscar_persona, 
    crear_persona, 
    about,verpersona, 
    eliminarpersona, 
    editarpersona)

from inicio.views import inicio, buscar_persona, crear_persona, about



app_name ='inicio'
urlpatterns = [
    path('', inicio, name='inicio'),
    path('buscar-persona/', buscar_persona, name='buscar_persona'),
    path('crear-persona/', crear_persona, name='crear_persona'),
    path('about/', about, name='about'),
    path('verpersona/<int:persona_id>/', verpersona, name='verpersona'),
    path('eliminarpersona/<int:persona_id>/', eliminarpersona, name='eliminarpersona'),
    path('editarpersona/<int:persona_id>/', editarpersona, name='editarpersona')
    
    ]

 

eventos/models.py
from django.db import models

#GEnero
class Fiesta(models.Model):
    salon=models.CharField(max_length=20)
    direccion=models.CharField(max_length=20)
    construido=models.DateTimeField()
    capacidad=models.IntegerField()
    imagen = models.ImageField(upload_to='imagenes_fiestas/', blank=True, null=True)
    
    
    def __str__(self):
        return f'{self.salon} - {self.direccion} - capacida: {self.capacidad}'

eventos/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import UpdateView
from eventos.models import Fiesta
from django.urls import reverse_lazy
from django.db.models import Q



#def crear_fiesta(request):
#    return HttpResponse('Crear Fiesta')


class CrearFiesta(CreateView):
    model = Fiesta
    template_name = "eventos/crear_fiesta.html"
    success_url = reverse_lazy('eventos:listado_fiesta')
    fields = ['salon', 'direccion', 'construido', 'capacidad', 'imagen']  # Incluye el campo de imagen
    

class ListadoFiesta(ListView):
    model = Fiesta
    template_name = "eventos/lista_fiesta.html"
    context_object_name = 'fiestas'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get('q')

        if query:
            queryset = queryset.filter(
                Q(salon__icontains=query) | 
                Q(direccion__icontains=query)
            )
        return queryset

class VerFiesta(DetailView):
    model= Fiesta
    template_name = "Eventos/ver_fiesta.html"
    
    
class EditarFiesta(UpdateView):
    model= Fiesta
    template_name = "Eventos/editar_fiesta.html"
    success_url = reverse_lazy('eventos:listado_fiesta')
    fields = ['salon', 'direccion', 'construido', 'capacidad', 'imagen']  # Incluye el campo de imagen

    
    
class EliminarFiesta(DeleteView):
    model= Fiesta
    template_name = "Eventos/eliminar_fiesta.html"
    success_url = reverse_lazy('eventos:listado_fiesta')
   # fields = ['salon', 'direccion','construido','capacidad']
   
   

eventos/templates/eventos/crear_fiesta.html
{% extends "Base.html" %}

{% block title_head %}             
   Nueva Sala
{% endblock title_head %} 

{% block h1_header %}
  Nueva Sala
{% endblock %}    

{% block main %}

<form action="{% url 'eventos:crear_fiesta' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %} 

    <br><br>

   {{ form }}
   
   <input type="submit" value="Crear">    
</form>

{% endblock main %}

eventos/templates/eventos/editar_fiesta.html
{% extends "Base.html" %}

{% block title_head %}             
 Editar Sala
{% endblock title_head %} 

{% block h1_header %}
    Editar: {{ Fiesta }}
{% endblock %}    

{% block main %}

<form action="{% url 'eventos:editar_fiesta' fiesta.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %} 

    <br><br>

    {{ form }}
   
    <input type="submit" value="Enviar">    
</form>

{% endblock main %}

eventos/templates/eventos/eliminar_fiesta.html
{% extends "Base.html" %}
{% load static %}

{% block title_head %}             
   Eliminar Sala
{% endblock title_head%} 


{% block h1_header %}
Eliminar Sala
{% endblock %}    

{% block main %}

<form action="{% url 'eventos:eliminar_fiesta' fiesta.id %}" method="POST" >

    {% csrf_token %} 

    <br><br>
    <p> Confirma eliminar Sala? </p>


   
<input type="submit" value="Confirmar">    
 
    


</form>




{% endblock main %}

eventos/templates/eventos/lista_fiesta.html
{% extends "Base.html" %}
{% load static %}

{% block title_head %}             
   Salas 
{% endblock title_head %} 

{% block h1_header %}
    Salas de reunio y trabajo
{% endblock %}    

{% block main %}

<!-- Formulario de búsqueda -->
<form method="GET" action="{% url 'eventos:listado_fiesta' %}">
    <input type="text" name="q" placeholder="Buscar fiesta" value="{{ request.GET.q }}">
    <button type="submit">Buscar</button>
</form>

{% if fiestas %}
    <h2>Salas disponibles:</h2>
    <ul>
        {% for f in fiestas %}
            <li>{{ f.salon }} - {{ f.direccion }}  
               | 
                <a href="{% url 'eventos:ver_fiesta' f.id %}"> Ver Sala </a>  |  
                <a href="{% url 'eventos:editar_fiesta' f.id %}"> Editar </a>  |         
                <a href="{% url 'eventos:eliminar_fiesta' f.id %}"> Eliminar </a></li> 
        {% endfor %}
    </ul>
{% else %}
    <p>No se encontraron Salas.</p>
{% endif %}

<!-- Botón 3D para crear nuevos salones -->
<a class="boton-3d" href="{% url 'eventos:crear_fiesta' %}">Nueva sala</a>


<style>
    .boton-3d {
        display: inline-block;
        padding: 15px 30px;
        font-size: 18px;
        font-family: Arial, sans-serif;
        color: white;
        background-color: #3498db;
        border: none;
        border-radius: 10px;
        box-shadow: 0px 5px 0px #2980b9, 0px 10px 15px rgba(0, 0, 0, 0.2);
        cursor: pointer;
        transition: all 0.2s ease;
        text-decoration: none; /* Para eliminar el subrayado del enlace */
    }

    .boton-3d:active {
        transform: translateY(5px);
        box-shadow: 0px 2px 0px #2980b9, 0px 5px 10px rgba(0, 0, 0, 0.2);
    }
</style>





{% endblock main %}

eventos/templates/eventos/ver_fiesta.html
{% extends "base.html" %}

{% load static %}

{% block title_head %}              
  Ver Sala 
{% endblock title_head%} 


{% block h1_header %}
  {{fiesta}}
{% endblock %}    


{% block main %}
<ul>
    <li>
       Salon: {{fiesta.salon}} 
    </li>
    <li>
       direccion: {{fiesta.direccion}}
    </li>
    <li>
       capacida: {{fiesta.capacidad}} 
    </li>
    <li>
      Imagen:
      {% if fiesta.imagen %}
          <img src="{{ fiesta.imagen.url }}" alt="Imagen de {{ fiesta.salon }}" style="max-width: 200px; max-height: 200px;">
      {% else %}
          <p>No hay imagen disponible para esta sala.</p>
      {% endif %}
   </li>

</ul>   

{% endblock main%}   