eventos/urls.py
from django.urls import path
from eventos import views

app_name='eventos'

urlpatterns = [
    path('fiestas/crear/', views.CrearFiesta.as_view(), name='crear_fiesta'),
    path('fiestas/', views.ListadoFiesta.as_view(), name='listado_fiesta'),
    path('fiestas/<int:pk>', views.VerFiesta.as_view(), name='ver_fiesta'),
    path('fiestas/<int:pk>/editar', views.EditarFiesta.as_view(), name='editar_fiesta'),
    path('fiestas/<int:pk>/eliminar', views.EliminarFiesta.as_view(), name='eliminar_fiesta')
    
]

gcoppariE3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inicio.urls')),
    path('eventos/', include('eventos.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios'))
   # path('chat/', include('chat.urls', namespace='chat')),  
    ]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
             

inicio/urls.py
from django.urls import path

from inicio.views import (
    inicio, 
    buscar_persona, 
    crear_persona, 
    about,verpersona, 
    eliminarpersona, 
    editarpersona)

from inicio.views import inicio, buscar_persona, crear_persona, about



app_name ='inicio'
urlpatterns = [
    path('', inicio, name='inicio'),
    path('buscar-persona/', buscar_persona, name='buscar_persona'),
    path('crear-persona/', crear_persona, name='crear_persona'),
    path('about/', about, name='about'),
    path('verpersona/<int:persona_id>/', verpersona, name='verpersona'),
    path('eliminarpersona/<int:persona_id>/', eliminarpersona, name='eliminarpersona'),
    path('editarpersona/<int:persona_id>/', editarpersona, name='editarpersona')
    
    ]

 

usuarios/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.conf import settings
from .views import editar_usuario,lista_usuarios,chat

app_name = 'usuarios'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    path('perfil/editar-perfil', views.editar_perfil, name='editar_perfil'),
    path('perfil/cambiar_pass', views.cambiar_pass.as_view(), name='cambiar_pass'),
    path('editar-usuario/<int:usuario_id>/', editar_usuario, name='editar_usuario'),
    path('lista-usuarios/', lista_usuarios, name='lista_usuarios'),
    path('chat/', views.chat_view, name='chat'),
    path('delete_message/<int:message_id>/', views.delete_message, name='delete_message'),
    path('borrar/<int:usuario_id>/', views.borrar_usuario, name='borrar_usuario')

    
    # chat 
    #path('chat/', views.chat_view, name='chat'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>
        {% block title_head %}   
            Template Base
        {% endblock title_head %} 
    </title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-light bg-light static-top">
        <div class="container">
            {% if request.user.is_authenticated %}
                <a class="boton-3d navbar-brand" href="{% url 'inicio:inicio' %}">Inicio</a>
                <a class="boton-3d navbar-brand" href="{% url 'inicio:crear_persona' %}">+ Empleado </a>
                <a class="boton-3d navbar-brand" href="{% url 'inicio:buscar_persona' %}">Lista empleados</a>
                <a class="boton-3d navbar-brand" href="{% url 'eventos:crear_fiesta' %}">+ Salas</a>
                <a class="boton-3d navbar-brand" href="{% url 'eventos:listado_fiesta' %}">Lista Salas</a>
                <a class="boton-3d navbar-brand" href="{% url 'inicio:about' %}">About</a>
           
                <a class="boton-3d navbar-brand" href="{% url 'usuarios:chat' %}">Chat</a>


                {% if request.user.is_superuser %}
                    <a class="boton-3d navbar-brand" href="{% url 'usuarios:lista_usuarios' %}">EditUsuarios</a>
                {% endif %}

                <!-- Perfil del usuario -->
                <a class="navbar-brand" href="{% url 'usuarios:editar_perfil' %}">
                    {% if request.user.datosextra.avatar %}
                        <img src="{{ request.user.datosextra.avatar.url }}" alt="Avatar" height="40px">
                    {% else %}
                        <img src="{% static 'images/default-avatar.png' %}" alt="Avatar por defecto" height="10px" >
                        
                    {% endif %}
                    <span>{{ request.user.username }}</span>
                </a>
                <!-- Logout -->
                <form action="{% url 'usuarios:logout' %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-secondary" value="Cerrar Sesión">
                </form>
            {% else %}
                <p class="navbar-text">Por favor, inicia sesión para acceder a las opciones del menú</p>
                <a class="btn btn-primary" href="{% url 'usuarios:login' %}">Login</a>
                <a class="btn btn-info" href="{% url 'usuarios:register' %}">Registrarse</a>
            {% endif %}
        </div>
    </nav>

    <!-- Header -->
    {% block header %}
    <header class="masthead">
        <div class="container position-relative">
            <div class="row justify-content-center">
                <div class="col-xl-6">
                    <div class="text-center text-white">
                        <h1 class="mb-5">
                        {% block h1_header %}
                            Prueba
                        {% endblock %}                                
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% endblock header %}

    <!-- Main Content -->
    <main>
        {% block main %}
        {% endblock main %}
    </main>

    <!-- Footer -->
    <footer class="footer bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                    <ul class="list-inline mb-2">
                        <li class="list-inline-item"><a href="{% url 'inicio:about' %}">About</a></li>
                        <li class="list-inline-item">⋅</li>
                        <li class="list-inline-item"><a href="#!">Contact</a></li>
                        <li class="list-inline-item">⋅</li>
                        <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                        <li class="list-inline-item">⋅</li>
                        <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                    </ul>
                    <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                </div>
                <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item me-4">
                            <a href="#!"><i class="bi-facebook fs-3"></i></a>
                        </li>
                        <li class="list-inline-item me-4">
                            <a href="#!"><i class="bi-twitter fs-3"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!"><i class="bi-instagram fs-3"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <!-- Bootstrap core JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS -->
    <script src="{% static 'js/scripts